prometheus:
  ingress:
    enabled: true
    hosts: [prometheus.k.maelvls.dev]
    annotations:
      kubernetes.io/ingress.class: traefik
      cert-manager.io/cluster-issuer: letsencrypt-staging
    tls:
      - hosts: [prometheus.k.maelvls.dev]
        secretName: prometheus-example-tls

alertmanager:
  ingress:
    enabled: true
    hosts: [alertmanager.k.maelvls.dev]
    annotations:
      kubernetes.io/ingress.class: traefik
      cert-manager.io/cluster-issuer: letsencrypt-staging
    tls:
      - hosts: [alertmanager.k.maelvls.dev]
        secretName: alertmanager-example-tls

grafana:
  ingress:
    enabled: true
    hosts: [grafana.k.maelvls.dev]
    annotations:
      kubernetes.io/ingress.class: traefik
      cert-manager.io/cluster-issuer: letsencrypt-staging
    tls:
      - hosts: [grafana.k.maelvls.dev]
        secretName: grafana-example-tls
  sidecar:
    dashboards: { enabled: true }
    datasources: { enabled: true }
