apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata: { name: letsencrypt-staging }
spec:
  acme:
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: mael.valais@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource used to store the account's private key.
      name: example-issuer-account-key-staging
    # Enable the HTTP01 challenge mechanism for this Issuer
    solvers:
      - http01:
          ingress:
            class: traefik
      # For some reasons, ingress hosts with a wildcard must use DNS01.
      - dns01:
          clouddns:
            project: august-period-234610
            serviceAccountSecretRef:
              name: jsonkey
              key: jsonkey

---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata: { name: letsencrypt-prod }
spec:
  acme:
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: mael.valais@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource used to store the account's private key.
      name: example-issuer-account-letsencrypt-prod
    # Enable the HTTP01 challenge mechanism for this Issuer
    solvers:
      - http01:
          ingress:
            class: traefik
      # For some reasons, ingress hosts with a wildcard must use DNS01.
      - dns01:
          clouddns:
            project: august-period-234610
            serviceAccountSecretRef:
              name: jsonkey
              key: jsonkey
