apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata: { name: letsencrypt-staging }
spec:
  acme:
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: mael.valais@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource used to store the account's private key.
      name: example-issuer-account-key-staging
    # Enable the HTTP01 challenge mechanism for this Issuer
    solvers:
      - http01:
          ingress:
            class: traefik
            ingressTemplate:
              metadata:
                annotations:
                  #traefik.ingress.kubernetes.io/router.entrypoints: "web"
                  #traefik.ingress.kubernetes.io/router.tls: "false"
                  #traefik.ingress.kubernetes.io/router.priority: "42"
      # For some reasons, ingress hosts with a wildcard must use DNS01.
      - dns01:
          clouddns:
            project: august-period-234610
            serviceAccountSecretRef:
              name: jsonkey
              key: jsonkey

---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: mael.valais@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource used to store the account's private key.
      name: example-issuer-account-letsencrypt-prod

      # Enable the HTTP01 challenge mechanism for this Issuer. Since Traefik
      # v2 (and its 'web/websecure entrypoints), the ingress created for the
      # ACME HTTP-01 challenge must be "web" only (instead of web+websecure).
      # See:
      # https://community.traefik.io/t/traefik-v2-not-working-on-ingress/5735/18
    solvers:
      - http01:
          ingress:
            class: traefik
            ingressTemplate:
              metadata:
                annotations:
                  #traefik.ingress.kubernetes.io/router.entrypoints: "web"
                  #traefik.ingress.kubernetes.io/router.tls: "false"
                  #traefik.ingress.kubernetes.io/router.priority: "42"

      # For some reasons, ingress hosts with a wildcard must use DNS01.
      - dns01:
          # Since I want cert-manager to use my top-level zone
          # maelvls.dev (since k.maelvls.dev is delegated to
          # ext-coredns), I have a Terraform target that creates a CNAME
          # record that redirects _acme-challenge.k.maelvls.dev  ->
          # _acme-challenge.maelvls.dev so that the challenge can be done
          # using my top-level zone (using my Cloud DNS account). See:
          # https://cert-manager.io/docs/configuration/acme/dns01/#delegated-domains-for-dns01
          cnameStrategy: Follow
          clouddns:
            project: august-period-234610
            serviceAccountSecretRef:
              name: jsonkey
              key: jsonkey
