# https://github.com/kubernetes-incubator/external-dns/blob/master/docs/tutorials/gke.md
# https://github.com/helm/charts/tree/master/stable/external-dns
# http://tech.paulcz.net/kubernetes-cookbook/gcp/gcp-external-dns/

sources: [ingress]

# When using the Google provider, specify the Google project (required when provider=google)
provider: google
google:
  project: august-period-234610
  serviceAccountSecret: external-dns # kubectl get secret

domainFilters: ["maelvls.dev"]

# These help tell which records are owned by external-dns.
registry: "txt"
txtOwnerId: "k8s"

## ensure RBAC is enabled
rbac:
  create: true
  apiVersion: v1

logLevel: debug