# https://github.com/bitnami/charts/tree/master/bitnami/external-dns

# I only use external-dns to set up the A record for my ext-coredns service
# (ns.k.maelvls.dev).
sources: [service]
namespace: ext-coredns

# When using the Google provider, specify the Google project (required when provider=google)
provider: google
google:
  project: august-period-234610
  serviceAccountSecret: jsonkey
  serviceAccountSecretKey: jsonkey

domainFilters: ["maelvls.dev"]

# These help tell which records are owned by external-dns.
registry: "txt"
txtOwnerId: "k8s"

## ensure RBAC is enabled
rbac:
  create: true
  apiVersion: v1

logLevel: debug
