ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts: [minio.k.maelvls.dev, "*.minio.k.maelvls.dev"]
  tls:
    - hosts: ["minio.k.maelvls.dev", "*.minio.k.maelvls.dev"]
      secretName: minio-example-tls
resources:
  requests:
    cpu: 0m
environment:
  MINIO_BROWSER: on
  MINIO_DOMAIN: minio.k.maelvls.dev

existingSecret: "minio"
