ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts: [minio.kube.maelvls.dev]
  tls:
    - hosts: [minio.kube.maelvls.dev]
      secretName: minio-example-tls
resources:
  requests:
    cpu: 0m