rbac: { enabled: true }
accessLogs: { enabled: true }
ssl: { enabled: true, enforced: true }

# https://docs.cert-manager.io/en/latest/tasks/issuing-certificates/ingress-shim.html#
dashboard:
  enabled: true
  domain: traefik.kube.maelvls.dev
  ingress:
    annotations:
      kubernetes.io/ingress.class: traefik
      cert-manager.io/cluster-issuer: letsencrypt-prod
    tls:
      - hosts: [traefik.kube.maelvls.dev]
        secretName: traefik-example-tls

kubernetes:
  namespaces:
    - awx
    - default
    - kube-system
    - quote-svc
    - vault
    - drone
    - traefik

# We use cloudflare. As soon as the LoadBalancer has an external IP, I want
# to add a 'A' record to cloudflare.
# https://github.com/kubernetes-incubator/external-dns/blob/master/docs/tutorials/cloudflare.md
service:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "*.kube.maelvls.dev"
