rbac:
  enabled: true
accessLogs:
  enabled: true
ssl:
  enabled: true
  enforced: true

# https://docs.cert-manager.io/en/latest/tasks/issuing-certificates/ingress-shim.html#
dashboard:
  enabled: true
  domain: traefik.kube.maelvls.dev
  ingress:
    annotations:
      kubernetes.io/ingress.class: traefik
      cert-manager.io/cluster-issuer: letsencrypt-prod
    tls:
      - hosts: [traefik.kube.maelvls.dev]
        secretName: traefik-example-tls

kubernetes:
  # If kubernetes.namespaces isn't set, all namespaces are watched.
  namespaces: []
  ingressEndpoint:
    # Updates each Ingress Status.LoadBalancer.Ingress so that external-dns may
    # be able to add records based on the Ingress.Spec.Tls or Spec.Rules.Host or
    # the annotation external-dns.alpha.kubernetes.io/hostname.
    #
    # https://github.com/containous/traefik/issues/2173#issuecomment-434271161
    publishedService: "traefik/traefik"

# I use Google's Cloud DNS. As soon as the LoadBalancer has an external IP, I
# want to add a 'A' record to Cloud DNS.
# https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/gke.md
#
# I can use that setting when I one a single A record that matches all
# subdomains like *.kube.maelvls.dev.
#
# I do not use it since I want each Ingress to have its own A record.
# service:
#   annotations:
#     external-dns.alpha.kubernetes.io/hostname: "*.kube.maelvls.dev"
